Don't use die until after it's defined.

diff --git a/unibuild/unibuild/libexec/common b/unibuild/unibuild/libexec/common
--- a/unibuild/unibuild/libexec/common
+++ b/unibuild/unibuild/libexec/common
@@ -2,8 +2,6 @@
 # Common functions for Unibuild
 #
 
-[ -d "${UNIBUILD}" ] || die "Can't find Unibuild directory."
-
 WHOAMI=$(basename $0)
 WHEREAMI=$(dirname $0)
 
@@ -18,6 +16,7 @@ die()
     exit 1
 }
 
+[ -d "${UNIBUILD}" ] || die "Can't find Unibuild directory."
 
 export UNIBUILD_COMMANDS="${UNIBUILD}/commands"
 export UNIBUILD_LIB="${UNIBUILD}/lib"
